name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Gradle (skip test)
        working-directory: ./workeezy
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Copy jar to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "workeezy/build/libs/*SNAPSHOT*.jar"
          target: "/home/ubuntu/workeezy-backend"

      - name: Deploy Backend (run deploy.sh)
        uses: appleboy/ssh-action@v0.1.7
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          envs: APPLICATION_PROPERTIES
          script: |
            echo "===== DEPLOY START ====="
            cd /home/ubuntu/workeezy-backend
            chmod +x deploy.sh
            ./deploy.sh
            echo "===== DEPLOY END ====="