name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Gradle (skip test)
        working-directory: ./workeezy
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Copy jar to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "workeezy/build/libs/*SNAPSHOT*.jar"
          target: "/home/ubuntu/workeezy-backend/workeezy/build/libs"

      - name: Restart Spring Boot on EC2
        uses: appleboy/ssh-action@v0.1.7
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          envs: APPLICATION_PROPERTIES
          script: |
            set -x
            echo "=== START SSH SCRIPT ==="
            pwd
            whoami

            cd /home/ubuntu/workeezy-backend || exit 1
            echo "PWD AFTER CD:"
            pwd

            echo "=== WRITE application-prod.yml ==="
            printf "%s" "$APPLICATION_PROPERTIES" > application-prod.yml
            ls -l application-prod.yml

            echo "=== CHECK JAR EXISTS ==="
            ls -l /home/ubuntu/workeezy-backend/workeezy/build/libs

            echo "=== KILL OLD PROCESS ==="
            pkill -15 -f 'java.*workeezy-0.0.1-SNAPSHOT.jar' || true
            sleep 2

            echo "=== START APP ==="
            nohup java -jar \
              /home/ubuntu/workeezy-backend/workeezy/build/libs/workeezy-0.0.1-SNAPSHOT.jar \
              --spring.profiles.active=prod \
              > /home/ubuntu/workeezy-backend/app.log 2>&1 &

            sleep 3
            pgrep -af java || echo "Spring not running"

            echo "=== CHECK LOG FILE ==="
            ls -l /home/ubuntu/workeezy-backend || true
            ls -l /home/ubuntu/workeezy-backend/app.log || true

            echo "=== END SSH SCRIPT ==="
