name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Gradle (skip test)
        working-directory: ./workeezy
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Copy jar to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "workeezy/build/libs/*SNAPSHOT*.jar"
          target: "/home/ubuntu/workeezy-backend/"

      - name: Restart Spring Boot on EC2
        uses: appleboy/ssh-action@v0.1.7
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          envs: APPLICATION_PROPERTIES
          script: |
            set -x
            echo "=== START SSH SCRIPT ==="
            pwd
            whoami

            cd /home/ubuntu/workeezy-backend || exit 1
            echo "PWD AFTER CD:"
            pwd

            echo "=== WRITE application.yml ==="
            echo "$APPLICATION_PROPERTIES" > application.yml
            ls -l application.yml

            echo "=== CHECK JAR EXISTS ==="
            ls -l /home/ubuntu/workeezy-backend/workeezy/build/libs

            echo "=== KILL OLD PROCESS ==="
            pgrep -f workeezy-0.0.1-SNAPSHOT.jar | xargs -r kill

            echo "=== TRY RUN JAVA (FOREGROUND) ==="
            java -jar /home/ubuntu/workeezy-backend/workeezy/build/libs/workeezy-0.0.1-SNAPSHOT.jar \
              --spring.profiles.active=prod


            echo "=== AFTER JAVA COMMAND ==="
            sleep 3
            pgrep -af workeezy || echo "Spring not running"

            echo "=== CHECK LOG FILE ==="
            ls -l /home/ubuntu/workeezy-backend || true
            ls -l /home/ubuntu/workeezy-backend/app.log || true

            echo "=== END SSH SCRIPT ==="
