name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Gradle (skip test)
        working-directory: ./workeezy
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Copy jar to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "workeezy/build/libs/*SNAPSHOT*.jar"
          target: "/home/ubuntu/workeezy-backend/"

      - name: Restart Spring Boot on EC2
        uses: appleboy/ssh-action@v0.1.7
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          envs: APPLICATION_PROPERTIES
          script: |
            cd /home/ubuntu/workeezy-backend

            echo "$APPLICATION_PROPERTIES" > application.yml

            pgrep -f 'workeezy-0.0.1-SNAPSHOT.jar' | xargs kill || true

            ls -l /home/ubuntu/workeezy-backend/workeezy/build/libs

            setsid nohup java -jar \
              /home/ubuntu/workeezy-backend/workeezy/build/libs/workeezy-0.0.1-SNAPSHOT.jar \
              --spring.profiles.active=prod \
              > /home/ubuntu/workeezy-backend/app.log 2>&1 < /dev/null &
              # overwrite app.log on each deploy

            sleep 3
            pgrep -f workeezy-0.0.1-SNAPSHOT.jar || echo "Spring not running"
