spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://workeezy.iptime.org:3306/workeezy
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate  # create, update, validate, none 중 선택
    show-sql: true  # SQL 쿼리 콘솔 출력
    properties:
      hibernate:
        format_sql: true  # SQL 포맷팅
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false  # OSIV 비활성화 (선택)

logging:
  level:
    org.hibernate.SQL: debug  # SQL 로깅
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # 파라미터 값 로깅
    org.springframework.security: DEBUG

jwt:
  secret: VEhJU19JU19BX1NVUEVSX0xPTkdfU0VDUkVUX0tFWV9GT1JfSldUX1RPS0VOXzEyMzQ1Njc4
  access-expiration-ms: 1800000      # 30분
  refresh-expiration-ms: 604800000   # 7일