spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://workeezy.iptime.org:3306
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update  # create, update, validate, none 중 선택
#    show-sql: true  # SQL 쿼리 콘솔 출력
    properties:
      hibernate:
        format_sql: true  # SQL 포맷팅
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false  # OSIV 비활성화 (선택)

logging:
  level:
    org.hibernate.SQL: debug  # SQL 로깅
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # 파라미터 값 로깅